#!/usr/bin/env sh


# -- Commands to add --
# Move a space to a different position


# -- Change Window Focus --

# change window focus within spaces visible on displays
hyper - h : yabai -m window --focus west || yabai -m display --focus west
hyper - j : yabai -m window --focus south || yabai -m display --focus south
hyper - k : yabai -m window --focus north || yabai -m display --focus north
hyper - l : yabai -m window --focus east || yabai -m display --focus east


# -- Change Space Focus --

# fast focus desktop
alt - tab : yabai -m space --focus recent
ctrl - left : yabai -m space --focus prev
ctrl - right : yabai -m space --focus next

alt - 1 : yabai -m space --focus 1;
alt - 2 : yabai -m space --focus 2;
alt - 3 : yabai -m space --focus 3;
alt - 4 : yabai -m space --focus 4;
alt - 5 : yabai -m space --focus 5;
alt - 6 : yabai -m space --focus 6;
alt - 7 : yabai -m space --focus 7;
alt - 8 : yabai -m space --focus 8;
alt - 9 : yabai -m space --focus 9;
alt - 0 : yabai -m space --focus 10;

# hyper - a : index="$(yabai -m query --windows | jq 'map(select(."app" == "Arc" and ."display" == 1))[0].id')" && yabai -m window --focus ${index}
# hyper - a : open /Applications/Arc.app
# hyper - s : index="$(yabai -m query --windows | jq 'map(select(."app" == "WezTerm" and ."display" == 1))[0].id')" && yabai -m window --focus ${index}
# hyper - s : open /Applications/WezTerm.app
# hyper - d : index="$(yabai -m query --windows | jq 'map(select(."app" == "Notion" and ."display" == 1))[0].id')" && yabai -m window --focus ${index}
# hyper - f : index="$(yabai -m query --windows | jq 'map(select(."app" == "DataGrip" and ."display" == 1))[0].id')" && yabai -m window --focus ${index}
# hyper - g : index="$(yabai -m query --windows | jq 'map(select(."app" == "IntelliJ" and ."display" == 1))[0].id')" && yabai -m window --focus ${index}
# hyper - h : index="$(yabai -m query --windows | jq 'map(select(."app" == "Microsoft Team (work or school)" and ."display" == 1))[0].id')" && yabai -m window --focus ${index}
# hyper - j : index="$(yabai -m query --windows | jq 'map(select(."app" == "Slack" and ."display" == 1))[0].id')" && yabai -m window --focus ${index}
# hyper - k : index="$(yabai -m query --windows | jq 'map(select(."app" == "Discord" and ."display" == 1))[0].id')" && yabai -m window --focus ${index}
# hyper - l : index="$(yabai -m query --windows | jq 'map(select(."app" == "Spotify" and ."display" == 1))[0].id')" && yabai -m window --focus ${index}
# hyper - ; : index="$(yabai -m query --windows | jq 'map(select(."app" == "Arc" and ."display" == 2))[0].id')" && yabai -m window --focus ${index}


# -- Move Windows Across Spaces --

# move window to space #
hyper - 1 : index="$(yabai -m query --windows | jq 'map(select(."has-focus" == true))[0].id')" && yabai -m window --space 1 && yabai -m window --focus ${index}
hyper - 2 : index="$(yabai -m query --windows | jq 'map(select(."has-focus" == true))[0].id')" && yabai -m window --space 2 && yabai -m window --focus ${index}
hyper - 3 : index="$(yabai -m query --windows | jq 'map(select(."has-focus" == true))[0].id')" && yabai -m window --space 3 && yabai -m window --focus ${index}
hyper - 4 : index="$(yabai -m query --windows | jq 'map(select(."has-focus" == true))[0].id')" && yabai -m window --space 4 && yabai -m window --focus ${index}
hyper - 5 : index="$(yabai -m query --windows | jq 'map(select(."has-focus" == true))[0].id')" && yabai -m window --space 5 && yabai -m window --focus ${index}
hyper - 6 : index="$(yabai -m query --windows | jq 'map(select(."has-focus" == true))[0].id')" && yabai -m window --space 6 && yabai -m window --focus ${index}
hyper - 7 : index="$(yabai -m query --windows | jq 'map(select(."has-focus" == true))[0].id')" && yabai -m window --space 7 && yabai -m window --focus ${index}
hyper - 8 : index="$(yabai -m query --windows | jq 'map(select(."has-focus" == true))[0].id')" && yabai -m window --space 8 && yabai -m window --focus ${index}
hyper - 9 : index="$(yabai -m query --windows | jq 'map(select(."has-focus" == true))[0].id')" && yabai -m window --space 9 && yabai -m window --focus ${index}
hyper - 0 : index="$(yabai -m query --windows | jq 'map(select(."has-focus" == true))[0].id')" && yabai -m window --space 10 && yabai -m window --focus ${index}

# hyper - 1 : yabai -m window --space 1 && yabai -m space --focus 1
# hyper - 2 : yabai -m window --space 2 && yabai -m space --focus 2
# hyper - 3 : yabai -m window --space 3 && yabai -m space --focus 3
# hyper - 4 : yabai -m window --space 4 && yabai -m space --focus 4
# hyper - 5 : yabai -m window --space 5 && yabai -m space --focus 5
# hyper - 6 : yabai -m window --space 6 && yabai -m space --focus 6
# hyper - 7 : yabai -m window --space 7 && yabai -m space --focus 7
# hyper - 8 : yabai -m window --space 8 && yabai -m space --focus 8
# hyper - 9 : yabai -m window --space 9 && yabai -m space --focus 9
# hyper - 0 : yabai -m window --space 10 && yabai -m space --focus 10


# -- Move Space to New Position --
# meh - 1: yabai -m space --move 1
# meh - 2: yabai -m space --move 2
# meh - 3: yabai -m space --move 3
# meh - 4: yabai -m space --move 4
# meh - 5: yabai -m space --move 5
# meh - 6: yabai -m space --move 6
# meh - 7: yabai -m space --move 7
# meh - 8: yabai -m space --move 8
# meh - 9: yabai -m space --move 9


# -- Modifying the Layout --

# maximize a window
hyper - f : yabai -m window --toggle zoom-fullscreen

# toggle window float
hyper - g : yabai -m window --toggle float --grid 4:4:1:1:2:2

# flip along y-axis
hyper - y : yabai -m space --mirror y-axis

# flip along x-axis
hyper - x : yabai -m space --mirror x-axis

# toggle window split type
hyper - s : yabai -m window --toggle split

# swap windows
hyper - w : yabai -m window --swap west
hyper - s : yabai -m window --swap south
hyper - n : yabai -m window --swap north
hyper - e : yabai -m window --swap east

# move window and split with target
ctrl + alt - h : yabai -m window --warp west
ctrl + alt - j : yabai -m window --warp south
ctrl + alt - k : yabai -m window --warp north
ctrl + alt - l : yabai -m window --warp east


# -- Modifying Window Size --

# balance out tree of windows (resize to occupy same area)
hyper - b : yabai -m space --balance

meh - left : yabai -m window --resize left:-20:0 | yabai -m window --resize right:-20:0
meh - down : yabai -m window --resize bottom:0:20 | yabai -m window --resize top:0:20
meh - up : yabai -m window --resize top:0:-20 | yabai -m window --resize bottom:0:-20
meh - right : yabai -m window --resize right:20:0 | yabai -m window --resize left:20:0

# move floating window
# shift + ctrl - a : yabai -m window --move rel:-20:0
# shift + ctrl - s : yabai -m window --move rel:0:20

# make floating window fill screen
# shift + alt - up     : yabai -m window --grid 1:1:0:0:1:1


##############################################################################


# create desktop, move window and follow focus - uses jq for parsing json (brew install jq)
# shift + cmd - n : yabai -m space --create && \
#                   index="$(yabai -m query --spaces --display | jq 'map(select(."is-native-fullscreen" == false))[-1].index')" && \
#                   yabai -m window --space "${index}" && \
#                   yabai -m space --focus "${index}"
